# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

COPY server/requirements.txt server/app.py server/api.py server/.flaskenv server/database.py server/database.sqlite3 server/model.py ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]
